[package]
name = "redos-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "redos"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.3", features = ["derive"] }
ignore = "0.4.20"
regex-nfa = { path = "../regex-nfa" }
redos = { path = "../redos" }
swc_common = { version = "0.32.1", features = ["tty-emitter"] }
swc_ecma_ast = "0.109.1"
swc_ecma_parser = { version = "0.140.0", features = ["typescript"] }
swc_ecma_visit = "0.95.1"
